---
linters:
  enable:
    - gofumpt

linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (net.Listener).Close
      - (*github.com/nwaples/tacplus.Server).Serve
